# Generated by Django 5.0 on 2023-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
