# Generated by Django 5.0 on 2023-12-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('price_before', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_now', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Game_description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('Game_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('tag', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.category')),
            ],
        ),
    ]
