# Generated by Django 5.0 on 2023-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
