# Generated by Django 5.0 on 2023-12-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, choices=[('Tranding', 'Tranding'), ('Most Played', 'Most Played')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
